name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python tests
      run: |
        python test_app.py # Replace with your test script

    - name: Build the project
      run: |
        npm install # Install Node.js dependencies
        npm run build # Build your project for production

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf /path/to/your/app/*
          cp -R ./dist/* /path/to/your/app/ # Assumes the build outputs to ./dist
    - name: Post deployment cleanup
      run: |
        # 这里可以添加部署后的清理工作，例如删除临时文件等
        rm -rf dist

# 定义环境变量，如果需要的话
env:
  CI: true
